services:
  crm_frontend:
    build:
      context: ./
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://82.25.86.78:8102}
    container_name: crm_frontend_container
    ports:
      - "8101:8103"
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://82.25.86.78:8102}